name: Documentation
description: 문서 추가 또는 수정을 요청합니다.
labels: ["documentation"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: 문서 작업 내용을 설명해주세요.
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: 작업 항목을 체크리스트로 작성해주세요.
      value: |
        - [ ]
    validations:
      required: false
