ALTER TABLE items ADD COLUMN category_code VARCHAR(32);

UPDATE items
SET category_code = CASE item_id
    WHEN 1 THEN 'ROOT_VEGETABLES'
    WHEN 2 THEN 'SEASONINGS'
    WHEN 3 THEN 'SEASONINGS'
    WHEN 4 THEN 'ROOT_VEGETABLES'
    WHEN 5 THEN 'ROOT_VEGETABLES'
    WHEN 6 THEN 'FRUITING_VEGETABLES'
    WHEN 7 THEN 'FRUITING_VEGETABLES'
    WHEN 8 THEN 'LEAFY_GREENS'
    WHEN 9 THEN 'ROOT_VEGETABLES'
    WHEN 10 THEN 'FRUITING_VEGETABLES'
    WHEN 11 THEN 'FRUITING_VEGETABLES'
    WHEN 12 THEN 'FRUITING_VEGETABLES'
    WHEN 13 THEN 'FRUITING_VEGETABLES'
    WHEN 14 THEN 'FRUITING_VEGETABLES'
    WHEN 15 THEN 'SEASONINGS'
    WHEN 16 THEN 'SEASONINGS'
    WHEN 17 THEN 'PEPPERS'
    WHEN 18 THEN 'PEPPERS'
    WHEN 19 THEN 'PEPPERS'
    WHEN 20 THEN 'PEPPERS'
    WHEN 21 THEN 'MUSHROOMS'
    WHEN 22 THEN 'MUSHROOMS'
    WHEN 23 THEN 'MUSHROOMS'
    WHEN 24 THEN 'SEASONINGS'
    WHEN 25 THEN 'SEASONINGS'
    WHEN 26 THEN 'LEAFY_GREENS'
    WHEN 27 THEN 'LEAFY_GREENS'
    WHEN 28 THEN 'LEAFY_GREENS'
    WHEN 29 THEN 'LEAFY_GREENS'
    WHEN 30 THEN 'SEASONINGS'
    WHEN 31 THEN 'SEASONINGS'
    WHEN 32 THEN 'ROOT_VEGETABLES'
    WHEN 33 THEN 'SEASONINGS'
    WHEN 34 THEN 'SEASONINGS'
    WHEN 35 THEN 'LEAFY_GREENS'
    WHEN 36 THEN 'LEAFY_GREENS'
    WHEN 37 THEN 'FRUITING_VEGETABLES'
    WHEN 38 THEN 'FRUITS'
    WHEN 39 THEN 'LEAFY_GREENS'
    WHEN 40 THEN 'LEAFY_GREENS'
    WHEN 41 THEN 'FRUITS'
    WHEN 42 THEN 'FRUITS'
    WHEN 43 THEN 'FRUITS'
    WHEN 44 THEN 'LEAFY_GREENS'
    WHEN 45 THEN 'LEAFY_GREENS'
    WHEN 46 THEN 'LEAFY_GREENS'
END
WHERE item_id BETWEEN 1 AND 46;

ALTER TABLE items ALTER COLUMN category_code SET NOT NULL;

ALTER TABLE items
    ADD CONSTRAINT ck_items_category_code
        CHECK (category_code IN (
            'ROOT_VEGETABLES',
            'LEAFY_GREENS',
            'FRUITING_VEGETABLES',
            'PEPPERS',
            'SEASONINGS',
            'MUSHROOMS',
            'FRUITS'
        ));
