CREATE TABLE stores (
    store_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kakao_place_id VARCHAR(30) NOT NULL,
    place_name VARCHAR(100) NOT NULL,
    place_url VARCHAR(500),
    category_name VARCHAR(255),
    address_name VARCHAR(255) NOT NULL,
    road_address_name VARCHAR(255),
    phone VARCHAR(30),
    category_group_code VARCHAR(20),
    category_group_name VARCHAR(50),
    longitude NUMERIC(13, 10),
    latitude NUMERIC(13, 10),
    distance INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_stores_kakao_place_id UNIQUE (kakao_place_id)
);

CREATE TABLE user_reports (
    report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    price INTEGER NOT NULL,
    unit VARCHAR(20) NOT NULL,
    amount NUMERIC(10, 3) NOT NULL,
    report_date DATE NOT NULL,
    public_price_diff INTEGER,
    price_diff_rate NUMERIC(5, 2),
    photo_url VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_reports_store FOREIGN KEY (store_id) REFERENCES stores (store_id) ON DELETE CASCADE,
    CONSTRAINT fk_user_reports_item FOREIGN KEY (item_id) REFERENCES items (item_id) ON DELETE CASCADE,
    CONSTRAINT fk_user_reports_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_user_reports_price_positive CHECK (price > 0),
    CONSTRAINT ck_user_reports_amount_positive CHECK (amount > 0)
);

CREATE INDEX idx_user_reports_item_report_date ON user_reports (item_id, report_date);
CREATE INDEX idx_user_reports_user_created_at ON user_reports (user_id, created_at);
