CREATE TABLE stores (
    store_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kakao_place_id VARCHAR(100) NOT NULL UNIQUE,
    store_name VARCHAR(200) NOT NULL,
    latitude NUMERIC(10, 7) NOT NULL,
    longitude NUMERIC(10, 7) NOT NULL,
    address_name VARCHAR(500),
    road_address_name VARCHAR(500),
    phone VARCHAR(100),
    place_url VARCHAR(2048)
);

CREATE TABLE store_favorites (
    store_favorite_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    store_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_store_favorites_user_store UNIQUE (user_id, store_id),
    CONSTRAINT fk_store_favorites_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_store_favorites_store
        FOREIGN KEY (store_id) REFERENCES stores (store_id) ON DELETE CASCADE
);

CREATE INDEX idx_store_favorites_user_id
    ON store_favorites (user_id);
