CREATE TABLE user_regions (
    user_region_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    region_id VARCHAR(10) NOT NULL,
    is_current BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_regions_user_region UNIQUE (user_id, region_id),
    CONSTRAINT fk_user_regions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_regions_region FOREIGN KEY (region_id) REFERENCES regions (region_id)
);

CREATE INDEX idx_user_regions_user_current ON user_regions (user_id, is_current);
CREATE UNIQUE INDEX uk_user_regions_current_user ON user_regions (user_id)
WHERE is_current = TRUE;
