-- 품목 이미지는 정책 문서의 Coupang Fresh 대표 이미지를 사전 업로드한
-- 공개 S3 객체의 고정 URL로 저장한다. 원본 주소는 scripts/upload-item-images.sh에 고정한다.
UPDATE items
SET item_image_url = CASE item_id
    WHEN 1 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/potato.jpg'
    WHEN 2 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/garlic.jpg'
    WHEN 3 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/onion.jpg'
    WHEN 4 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/sweet-potato.jpg'
    WHEN 5 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/carrot.jpg'
    WHEN 6 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/tomato.jpg'
    WHEN 7 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/bell-pepper.jpg'
    WHEN 8 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/napa-cabbage.png'
    WHEN 9 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/radish.jpg'
    WHEN 10 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/zucchini.jpg'
    WHEN 11 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/zucchini-2.jpg'
    WHEN 12 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/cucumber.jpg'
    WHEN 13 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/cherry-tomato.jpg'
    WHEN 14 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/cherry-tomato.jpg'
    WHEN 15 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/green-onion.jpg'
    WHEN 16 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/chives.jpg'
    WHEN 17 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/green-chili.jpg'
    WHEN 18 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/shishito-pepper.jpg'
    WHEN 19 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/cheongyang-chili.jpg'
    WHEN 20 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/cucumber-chili.jpg'
    WHEN 21 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/oyster-mushroom.jpg'
    WHEN 22 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/enoki-mushroom.jpg'
    WHEN 23 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/king-oyster-mushroom.jpg'
    WHEN 24 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/sesame.jpg'
    WHEN 25 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/peanut.jpg'
    WHEN 26 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/cabbage.jpg'
    WHEN 27 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/spinach.jpg'
    WHEN 28 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/young-napa-cabbage.jpg'
    WHEN 29 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/young-radish.jpg'
    WHEN 30 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/dried-chili.jpg'
    WHEN 31 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/red-chili.jpg'
    WHEN 32 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/ginger.jpg'
    WHEN 33 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/red-pepper-powder-domestic.jpg'
    WHEN 34 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/red-pepper-powder-imported.jpg'
    WHEN 35 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/water-dropwort.jpg'
    WHEN 36 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/perilla-leaf.jpg'
    WHEN 37 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/paprika.jpg'
    WHEN 38 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/melon.jpg'
    WHEN 39 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/broccoli.jpg'
    WHEN 40 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/baby-napa-cabbage.png'
    WHEN 41 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/watermelon.jpg'
    WHEN 42 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/korean-melon.jpg'
    WHEN 43 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/strawberry.jpg'
    WHEN 44 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/red-lettuce.jpg'
    WHEN 45 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/green-lettuce.jpg'
    WHEN 46 THEN 'https://marketgo-images.s3.ap-northeast-2.amazonaws.com/images/items/mustard-leaf.jpg'
END
WHERE item_id BETWEEN 1 AND 46;
