CREATE TABLE items (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name VARCHAR(50) NOT NULL,
    default_unit VARCHAR(20),
    item_image_url VARCHAR(255)
);

CREATE TABLE public_prices (
    public_price_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL,
    region_id VARCHAR(20) NOT NULL,
    price INTEGER NOT NULL,
    price_date DATE NOT NULL,
    CONSTRAINT fk_public_prices_item
        FOREIGN KEY (item_id) REFERENCES items (item_id) ON DELETE CASCADE
);

CREATE INDEX idx_public_prices_item_region_date
    ON public_prices (item_id, region_id, price_date);

INSERT INTO items (item_name, default_unit)
VALUES
    ('감자', '1kg'),
    ('양파', '1kg'),
    ('대파', '1단');

INSERT INTO public_prices (item_id, region_id, price, price_date)
SELECT item_id, '1121510100', price, CURRENT_DATE
FROM (
    VALUES
        ('감자', 3500),
        ('양파', 2800),
        ('대파', 2200)
) AS seed(item_name, price)
JOIN items ON items.item_name = seed.item_name;
