CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(20) NOT NULL,
    provider_subject VARCHAR(100) NOT NULL,
    email VARCHAR(320),
    name VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    CONSTRAINT uk_users_provider_subject UNIQUE (provider, provider_subject)
);
