CREATE TABLE news_articles (
    news_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    summary VARCHAR(2000) NOT NULL,
    original_url VARCHAR(2048) NOT NULL UNIQUE,
    thumbnail_url VARCHAR(2048),
    published_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_news_articles_published_at_news_id
    ON news_articles (published_at DESC, news_id DESC);
